<?php
$data = array (
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '积分兑换商品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '46',
    'name' => '积分兑换商品',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '有机蔬菜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '有机蔬菜',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '果菜类',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 1,
    'id' => '23',
    'name' => '果菜类',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '菜花/西兰花/包心菜/大白菜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '30',
    'name' => '菜花/西兰花/包心菜/大白菜',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '瓜类/西红柿类',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 1,
    'id' => '27',
    'name' => '瓜类/西红柿类',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '叶菜类',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 1,
    'id' => '24',
    'name' => '叶菜类',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '葱姜蒜',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '31',
    'name' => '葱姜蒜',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '豆角/芸豆类',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '28',
    'name' => '豆角/芸豆类',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '根茎类',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '26',
    'level' => 1,
    'id' => '29',
    'name' => '根茎类',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '肉类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '56',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '肉类',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '海鲜',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '44',
    'name' => '海鲜',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '家禽类',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '32',
    'name' => '家禽类',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '猪肉',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '25',
    'name' => '猪肉',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '牛羊肉',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '26',
    'name' => '牛羊肉',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '粮油',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '58',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '21',
    'name' => '粮油',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '调味品',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '调味品',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
    'level' => 1,
    'id' => '33',
    'name' => '大米',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '杂粮',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
    'level' => 1,
    'id' => '38',
    'name' => '杂粮',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '面粉面条',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '35',
    'name' => '面粉面条',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '56',
    'level' => 1,
    'id' => '34',
    'name' => '食用油',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '南北干货',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '南北干货',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '水果产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '59',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '水果产品',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '苹果类',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '43',
    'name' => '苹果类',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '进口水果',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '进口水果',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '国产水果',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '41',
    'name' => '国产水果',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '干果',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '45',
    'name' => '干果',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '热带水果',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '热带水果',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '有机水果',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => '有机水果',
  ),
);
?>